// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StartupBackend.Data;

#nullable disable

namespace StartupBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702082443_UpdateProgramsTable")]
    partial class UpdateProgramsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StartupBackend.Models.Accounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoTenNguoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HocHam")
                        .HasColumnType("text");

                    b.Property<string>("HocVi")
                        .HasColumnType("text");

                    b.Property<string>("MaCTDT")
                        .HasColumnType("text");

                    b.Property<string>("MaKhoa")
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("integer");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrinhDoChuyenMon")
                        .HasColumnType("text");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaCTDT");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.HasIndex("VaiTroId");

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@system.com",
                            HoTenNguoiDung = "Root Admin",
                            MatKhau = "$2a$11$MI7VEPRdZ9V3H9p1LU.57OvSFgPjViRCDvgjW/mB5oy1xpjn5PdPu",
                            NgayTao = new DateTime(2026, 7, 2, 8, 24, 40, 681, DateTimeKind.Utc).AddTicks(377),
                            TenDangNhap = "admin",
                            TenantId = "HCMCOU",
                            TrangThai = "Hoạt động",
                            VaiTroId = 1
                        });
                });

            modelBuilder.Entity("StartupBackend.Models.Khoas", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasColumnType("text");

                    b.Property<string>("MaCTDT")
                        .HasColumnType("text");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaKhoa");

                    b.HasIndex("MaCTDT");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("StartupBackend.Models.PhanCongBienSoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguoiBienSoanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("NguoiBienSoanId");

                    b.ToTable("PhanCongBienSoans");
                });

            modelBuilder.Entity("StartupBackend.Models.Programs", b =>
                {
                    b.Property<string>("MaCTDT")
                        .HasColumnType("text");

                    b.Property<string>("HinhThuc")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NamApDung")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NganhDaoTao")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySuaDoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiSuaDoi")
                        .HasColumnType("text");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenCTDT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenCTDTEng")
                        .HasColumnType("text");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaCTDT");

                    b.ToTable("ChuongTrinhDaoTaos");
                });

            modelBuilder.Entity("StartupBackend.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VaiTros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenVaiTro = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            TenVaiTro = "MANAGER"
                        },
                        new
                        {
                            Id = 3,
                            TenVaiTro = "COMPILER"
                        });
                });

            modelBuilder.Entity("StartupBackend.Models.Subjects", b =>
                {
                    b.Property<string>("MaMonHoc")
                        .HasColumnType("text");

                    b.Property<string>("ChuongTrinhDaoTaoMa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SoTinChiLyThuyet")
                        .HasColumnType("integer");

                    b.Property<int>("SoTinChiThucHanh")
                        .HasColumnType("integer");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrangThaiHoanThanh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaMonHoc");

                    b.HasIndex("ChuongTrinhDaoTaoMa");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("StartupBackend.Models.Accounts", b =>
                {
                    b.HasOne("StartupBackend.Models.Programs", "ChuongTrinhDaoTao")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaCTDT");

                    b.HasOne("StartupBackend.Models.Khoas", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa");

                    b.HasOne("StartupBackend.Models.Roles", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhDaoTao");

                    b.Navigation("Khoa");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("StartupBackend.Models.Khoas", b =>
                {
                    b.HasOne("StartupBackend.Models.Programs", "ChuongTrinhDaoTao")
                        .WithMany()
                        .HasForeignKey("MaCTDT");

                    b.Navigation("ChuongTrinhDaoTao");
                });

            modelBuilder.Entity("StartupBackend.Models.PhanCongBienSoan", b =>
                {
                    b.HasOne("StartupBackend.Models.Subjects", "MonHoc")
                        .WithMany("PhanCongBienSoans")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StartupBackend.Models.Accounts", "NguoiBienSoan")
                        .WithMany("PhanCongBienSoans")
                        .HasForeignKey("NguoiBienSoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiBienSoan");
                });

            modelBuilder.Entity("StartupBackend.Models.Subjects", b =>
                {
                    b.HasOne("StartupBackend.Models.Programs", "ChuongTrinhDaoTao")
                        .WithMany("MonHocs")
                        .HasForeignKey("ChuongTrinhDaoTaoMa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhDaoTao");
                });

            modelBuilder.Entity("StartupBackend.Models.Accounts", b =>
                {
                    b.Navigation("PhanCongBienSoans");
                });

            modelBuilder.Entity("StartupBackend.Models.Programs", b =>
                {
                    b.Navigation("MonHocs");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("StartupBackend.Models.Roles", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("StartupBackend.Models.Subjects", b =>
                {
                    b.Navigation("PhanCongBienSoans");
                });
#pragma warning restore 612, 618
        }
    }
}
